name: 'Install anchore/quill'
description: 'Install and cache the Anchore Quill binary with checksum verification'
inputs:
  version:
    description: 'Quill version to install'
    required: true
  cache:
    description: 'Enable caching of the binary'
    required: false
    default: 'true'

outputs:
  version:
    description: 'The version of Quill that was installed'
    value: ${{ inputs.version }}
  cache-hit:
    description: 'Whether the binary was restored from cache'
    value: ${{ steps.cache-quill.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      id: cache-quill
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ~/.local/bin/quill
        key: quill-linux-${{ runner.arch }}-${{ inputs.version }}

    - name: "Run script: install quill"
      if: ${{ inputs.cache == 'false' || steps.cache-quill.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"

        case "$(uname -m)" in
          x86_64) ARCH="amd64" ;;
          aarch64) ARCH="arm64" ;;
          *) echo "Unsupported architecture: $(uname -m)"; exit 1 ;;
        esac

        PLATFORM="linux_${ARCH}"

        echo "Installing Quill v${VERSION} for ${PLATFORM}"

        TEMP_DIR=$(mktemp -d)
        cd "$TEMP_DIR"

        curl -L "https://github.com/anchore/quill/releases/download/v${VERSION}/quill_${VERSION}_${PLATFORM}.tar.gz" -o quill.tar.gz
        curl -L "https://github.com/anchore/quill/releases/download/v${VERSION}/quill_${VERSION}_checksums.txt" -o checksums.txt
        sha256sum -c <(grep "quill_${VERSION}_${PLATFORM}.tar.gz" checksums.txt)

        tar xzf quill.tar.gz
        mkdir -p ~/.local/bin
        mv quill ~/.local/bin/
        chmod +x ~/.local/bin/quill

        cd /
        rm -rf "$TEMP_DIR"

        echo "Quill ${VERSION} installed successfully"

    - name: "Run script: install quill systemwide"
      shell: bash
      run: |
        sudo cp ~/.local/bin/quill /usr/local/bin/
        chmod +x /usr/local/bin/quill
        quill --version
