version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# replace per-arch macos binaries with a single universal binary
universal_binaries:
  - replace: true
    # hooks:
    #   post:
    #     - cmd: quill sign-and-notarize "{{ .Path }}"
    #       env:
    #         # - QUILL_AD_HOC={{ .IsSnapshot }}
    #         # - QUILL_DRY_RUN={{ .IsSnapshot }}
    #         - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log

source:
  enabled: true

sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Os | tolower }}-
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: mccutchen
    name: ghavm
  draft: false
  prerelease: auto
  mode: replace

# Adapted from official docs:
# https://goreleaser.com/customization/notarize/#cross-platform
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'

      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"

      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

        # this can apparently take a long time?
        wait: true
        timeout: 60m
